### ISSUE TITLE
XML config gets corrupted when config file size drops

### ISSUE THREAD

**Issue by mavadat** [Readify/TeamFlash#17]
### Issue
XML config file (currently misleadingly named as ```config.json```) can get corrupted. It appears to happen when size XML config is changed and the new file is smaller in terms of size.

TeamFlash appear to open config file for write, and then write new config over existing config. If new config is bigger in size then all good; however, when new config is smaller then left-overs from previous config file result into corrupted XML config file.

### What to Do
Over-write. So that previous content is wiped out in favor of fresh new XML content.

**Comment by mavadat** [comment]
Submitted [PR](https://github.com/Readify/TeamFlash/pull/18) to address this issue.

**Comment by aaronpowell** [comment]
PR merged, thanks @mavadat :)
